name: Build opencloudos rootfs

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:

env:
  TZ: America/New_York

jobs:
  kdevbuild:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - set_vendor: opencloudos
            set_version: "8"
          - set_vendor: opencloudos
            set_version: "8.10"
          - set_vendor: opencloudos
            set_version: "8.6"
          - set_vendor: opencloudos
            set_version: "8.8"
          - set_vendor: opencloudos
            set_version: "9"
          - set_vendor: opencloudos
            set_version: "9.0"
          - set_vendor: opencloudos
            set_version: "9.2"
          - set_vendor: opencloudos
            set_version: "9.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show environment
        id: basic_info
        run: |
          nproc
          uname -a
          cat /etc/*release
          free -h
          mount
          df -h
          cat /proc/cpuinfo
          cat /proc/meminfo

      - name: Create simulated physical disk
        run: |
          mnt_size=$(expr $(df -h /mnt | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 1)
          root_size=$(expr $(df -h / | tail -1 | awk '{print $4}' | sed 's/[[:alpha:]]//g' | sed 's/\..*//') - 4)
          sudo truncate -s "${mnt_size}"G /mnt/mnt.img
          sudo truncate -s "${root_size}"G /root.img
          sudo losetup /dev/loop6 /mnt/mnt.img
          sudo losetup /dev/loop7 /root.img
          sudo pvcreate /dev/loop6
          sudo pvcreate /dev/loop7
          sudo vgcreate github /dev/loop6 /dev/loop7
          sudo lvcreate -n runner -l 100%FREE github
          sudo mkfs.xfs /dev/github/runner
          sudo mkdir -p /builder
          sudo mount /dev/github/runner /builder
          sudo chown -R runner.runner /builder
          df -Th

      - name: Run build in Ubuntu 22.04 container
        working-directory: /builder/
        run: |
          pwd
          sudo /bin/cp -a ${{ github.workspace }}/* .
          ls -alh
          sudo docker run --rm \
            --privileged \
            --cap-add SYS_ADMIN \
            -v /dev:/dev \
            -v /builder:/workspace \
            -w /workspace \
            -e set_vendor=${{ matrix.set_vendor }} \
            -e set_version=${{ matrix.set_version }} \
            ubuntu:22.04 \
            bash -c "
              chmod +x /workspace/kdevbuild/build-opencloudos-rootfs.sh ;
              /workspace/kdevbuild/build-opencloudos-rootfs.sh
            "

      - name: List build output
        run: |
          ls -alh  /builder/release/*
          md5sum /builder/release/*

      - name: Upload Image to Release
        uses: ncipollo/release-action@main
        with:
          tag: opencloudos-rootfs
          artifacts: /builder/release/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: | # opencloudos rootfs

            1. 镜像命名规则: opencloudos_$VERSION_$ARCH.rar 格式命名
            2. 母盘镜像获取方式： https://mirrors.cloud.tencent.com/opencloudos/
            3. 所有资源均来自官方发布，严格遵守法律法规

