name: Build ubuntu rootfs

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:

env:
  TZ: America/New_York

jobs:
  kdevbuild:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - set_vendor: ubuntu
            set_release: bionic
            set_version: 18.04
            set_arch: amd64
          - set_vendor: ubuntu
            set_release: bionic
            set_version: 18.04
            set_arch: arm64
          # ubuntu 20.04
          - set_vendor: ubuntu
            set_release: focal
            set_version: 20.04
            set_arch: amd64
          - set_vendor: ubuntu
            set_release: focal
            set_version: 20.04
            set_arch: arm64
          # ubuntu 22.04
          - set_vendor: ubuntu
            set_release: jammy
            set_version: 22.04
            set_arch: amd64
          - set_vendor: ubuntu
            set_release: jammy
            set_version: 22.04
            set_arch: arm64
          # ubuntu 24.04
          - set_vendor: ubuntu
            set_release: noble
            set_version: 24.04
            set_arch: amd64
          - set_vendor: ubuntu
            set_release: noble
            set_version: 24.04
            set_arch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show environment
        id: basic_info
        run: |
          nproc
          uname -a
          cat /etc/*release
          free -h
          mount
          df -h
          cat /proc/cpuinfo
          cat /proc/meminfo

      - name: Run build in Ubuntu 22.04 container
        working-directory: ${{ github.workspace }}
        run: |
          pwd
          ls -alh
          sudo docker run --rm \
            --privileged \
            --cap-add SYS_ADMIN \
            -v /dev:/dev \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e set_vendor=${{ matrix.set_vendor }} \
            -e set_release=${{ matrix.set_release }} \
            -e set_version=${{ matrix.set_version }} \
            -e set_arch=${{ matrix.set_arch }} \
            ubuntu:22.04 \
            bash -c "
              chmod +x /workspace/kdevbuild/build-ubuntu-rootfs.sh ;
              /workspace/kdevbuild/build-ubuntu-rootfs.sh
            "

      - name: List build output
        run: |
          ls -alh  ${{ github.workspace }}/release/*
          md5sum ${{ github.workspace }}/release/*

      - name: Upload Image to Release
        uses: ncipollo/release-action@main
        with:
          tag: ubuntu-rootfs
          artifacts: ${{ github.workspace }}/release/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: | # ubuntu rootfs

            1. 镜像命名规则: ubuntu_$RELEASE_$VERSION_$ARCH.rar 格式命名
            2. 母盘镜像获取方式： https://cloud-images.ubuntu.com/daily/server/

